"""Adjuntos PDF por rutina

Revision ID: 295a467ba9f7
Revises: 7e029f307b2d
Create Date: 2026-08-23 12:18:07.093725
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '295a467ba9f7'
down_revision: str | None = '7e029f307b2d'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=80), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    with op.batch_alter_table('routine_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routine_attachments_routine_id'), ['routine_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('routine_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routine_attachments_routine_id'))

    op.drop_table('routine_attachments')
    # ### end Alembic commands ###
