"""Anotaciones de peso por jugador

Revision ID: d63f0d109519
Revises: 295a467ba9f7
Create Date: 2026-08-29 16:31:48.419120
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd63f0d109519'
down_revision: str | None = '295a467ba9f7'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_prescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('routine_exercise_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_load_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['routine_exercise_id'], ['routine_exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('routine_exercise_id', 'user_id', name='uq_anotacion_jugador')
    )
    with op.batch_alter_table('exercise_prescriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_prescriptions_routine_exercise_id'), ['routine_exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_prescriptions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_prescriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_prescriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_exercise_prescriptions_routine_exercise_id'))

    op.drop_table('exercise_prescriptions')
    # ### end Alembic commands ###
